# Generated by Django 4.1 on 2022-08-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_image_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
