# Generated by Django 4.1 on 2022-08-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.CharField(default='h', max_length=100),
        ),
    ]
