# Generated by Django 4.1 on 2022-08-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_image_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploaded',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
