# Generated by Django 4.1 on 2022-08-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_remove_image_uploaded_remove_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.ImageField(default='blank.png', upload_to='images'),
        ),
    ]
