# Generated by Django 4.1 on 2022-08-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_remove_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='blank.png', upload_to='coverimages'),
        ),
    ]
