# Generated by Django 4.1 on 2022-08-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_profile_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
