# Generated by Django 4.1 on 2022-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_profile_dob_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(default='room', max_length=100)),
                ('roomid', models.IntegerField()),
            ],
        ),
    ]
