# Generated by Django 4.1 on 2022-09-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_remove_messageroom_id_remove_messageroom_messageroom_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='cmessage',
        ),
    ]
