# Generated by Django 4.1.3 on 2022-12-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_saveotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_verification',
            field=models.BooleanField(default=True),
        ),
    ]
